webtalk_init -webtalk_dir /home/spereira/projects/PhD/ultra96_axiDMA/project_DMA/project_DMA.sdk/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2020-06-02 14:58:22" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2018.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211311721_1777553580_0_807" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "fioksm2ea1bgrju5hg15mojgn7" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2018.3_14" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "14" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 20.04 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3500.000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16,666 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1591097514000" -context "sdk\\\\bsp/1591097514000"
webtalk_add_data -client sdk -key hwid -value "1590600123000" -context "sdk\\\\bsp/1591097514000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1591097514000"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\bsp/1591097514000"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1591097514000"
webtalk_add_data -client sdk -key uid -value "1591097516000" -context "sdk\\\\application/1591097516000"
webtalk_add_data -client sdk -key hwid -value "1590600123000" -context "sdk\\\\application/1591097516000"
webtalk_add_data -client sdk -key bspid -value "1591097514000" -context "sdk\\\\application/1591097516000"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1591097516000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1591097516000"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\application/1591097516000"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1591097516000"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1591097516000"
webtalk_add_data -client sdk -key Procused -value "psu_cortexa53" -context "sdk\\\\application/1591097516000"
webtalk_add_data -client sdk -key projSize -value "398.046875" -context "sdk\\\\application/1591097516000"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1591106302182"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1591106302182"
webtalk_add_data -client sdk -key BootgenCount -value "3" -context "sdk\\\\bsp/1591106302182"
webtalk_add_data -client sdk -key DebugCount -value "0" -context "sdk\\\\bsp/1591106302182"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1591106302182"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1591106302182"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1591106302182"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1591106302182"
webtalk_transmit -clientid 15410768 -regid "211311721_1777553580_0_807" -xml /home/spereira/projects/PhD/ultra96_axiDMA/project_DMA/project_DMA.sdk/webtalk/usage_statistics_ext_sdk.xml -html /home/spereira/projects/PhD/ultra96_axiDMA/project_DMA/project_DMA.sdk/webtalk/usage_statistics_ext_sdk.html -wdm /home/spereira/projects/PhD/ultra96_axiDMA/project_DMA/project_DMA.sdk/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
